### ISSUE TITLE
nUserdataLen = 0

### ISSUE THREAD

**Issue by mdevans** [dismantl/ImprovedReflectiveDLLInjection#1]
rdi.sln building fine under VS2015
inject working fine but nUserdataLen is always 0 in MyFunction.
Cause?

```
MyFunction(LPVOID lpUserdata, DWORD nUserdataLen)
```

**Comment by dismantl** [comment]
What command line parameters are you passing to the program when you run it? MyFunction() is passed `argv[1]` as its first parameter and `strlen(argv[1]) + 1` as the second parameter, see https://github.com/dismantl/ImprovedReflectiveDLLInjection/blob/master/inject/src/Inject.c#L102.

**Comment by mdevans** [comment]
I am passing "Hello" as argv[1]
